### ISSUE TITLE
Exception thrown when using Symfony 3.3 and translator

### ISSUE THREAD

**Issue by ste93cry** [sonatra/sonatra-security-bundle#13]
Using Symfony 3.3 the following exception is thrown when trying to use the translator:

>"You have requested a non-existent service "resource_files"

This happens because in Symfony 3.2 and lower the `Symfony\Bundle\FrameworkBundle\Translation\Translator` class accepted 3 arguments, while in newer versions a new argument was added before the `$options` parameter. Your [`TranslatorPass`](https://github.com/sonatra/sonatra-security-bundle/blob/f5a49fd7089d719991bc9b3c62ced4f5e468fa97/DependencyInjection/Compiler/TranslatorPass.php) class merges the resource files with the wrong argument (which is now an array of loaders services IDs) and generates the error. The code should be updated to reflect the change by doing different things based on the number of arguments of the service

**Comment by francoispluchino** [comment]
Indeed, I haven't yet tested with version 3.3, and it's a bug with the new version of Symfony.

**Comment by ste93cry** [comment]
As this is blocker for the usage of this bundle with that version of Symfony and given that there is no way to make it working without fixing it at core, do you have any timeline of when this will be fixed? If this is going to take some time I could prepare a PR, because actually this bug is breaking my project

**Comment by francoispluchino** [comment]
Any help is welcome, do if you want to fix this bug, I take :)

**Comment by francoispluchino** [comment]
Fixed by #14.
