### ISSUE TITLE
class Abstract Filter not found

### ISSUE THREAD

**Issue by Jir4** [sonatra/sonatra-security-bundle#16]
Hi guys,

I'm trying this bundle and i've got an error when i use a command.

For exemple : 
```
php bin/console doctrine:schema:update --force
PHP Fatal error:  Class 'Sonatra\Component\DoctrineExtensions\Filter\AbstractFilter' not found in /myproject/vendor/sonatra/security/Doctrine/ORM/Filter/SharingFilter.php on line 27
```

I followed the documentation and add : 
```config.yml
    orm:
        entity_managers:
            default:
                filters:
                    sonatra_sharing:
                        class:      Sonatra\Component\Security\Doctrine\ORM\Filter\SharingFilter
                        enabled:    true
```
in my config.yml.

Did i forgot something ?

Cheers

PS: tested with symfony 3.3.5, php 7.0.20

**Comment by francoispluchino** [comment]
If you want to use the Sharing Filter, you must add the optional depencency `sonatra/doctrine-extensions`:

```
$ composer require sonatra/doctrine-extensions: "^1.0.0@dev"
```
I should add this info in doc.

**Comment by Jir4** [comment]
I'm not sure about using it, i just followed the doc

**Comment by francoispluchino** [comment]
Precisely, you must add this dependency in order to use the sharing filter.

**Comment by Jir4** [comment]
You can close this issues as soon as the doc is upated i guess

**Comment by francoispluchino** [comment]
Added by 6b1197f718827c0ad5249626c5141868efe52482.
